### ISSUE TITLE
Reference Material / Put these links in wiki or README

### ISSUE THREAD

**Issue by torch2424** [torch2424/aesthetic-css#1]
Build System:

https://github.com/oxalorg/sakura

Visuals:

http://httpsters.me/ @davidnuon

https://www.reddit.com/r/VaporwaveAesthetics/

https://codepen.io/CSWApps/pen/YyerKb

https://codepen.io/geeksmarter/pen/akGJbm

https://codepen.io/era_eric_og/pen/apbVpN

https://codepen.io/Aests/pen/bwzBRk

**Comment by echo-exe** [comment]
https://icons8.com/articles/html-nostalgia-10-things-from-the-90s/

**Comment by echo-exe** [comment]
https://github.com/kristopolous/BOOTSTRA.386

**Comment by echo-exe** [comment]
http://wcerfgba.github.io/AESTHETIC.css/

**Comment by echo-exe** [comment]
https://github.com/rozap/vaporwave

**Comment by echo-exe** [comment]
https://github.com/LinkCable/vapor

**Comment by echo-exe** [comment]
https://www.hipsthetic.com/5-essential-vaporwave-fonts/

**Comment by torch2424** [comment]
http://www.colourlovers.com/palette/3636765/seapunk_vaporwave

**Comment by torch2424** [comment]
Glitch Effects:

https://codepen.io/FelixRilling/pen/vNJoMy

https://codepen.io/indefiniteloop/pen/VWmdbm

https://css-tricks.com/glitch-effect-text-images-svg/

**Comment by torch2424** [comment]
https://win95.ajf.me/win95.html

**Comment by echo-exe** [comment]
http://www.spycolor.com/004e98

windows xp colors

**Comment by torch2424** [comment]
http://idyle.com/wp-content/uploads/2012/12/tray-minimizer-screenshot-02_WinXP.gif

https://www.youtube.com/watch?v=QE2ztMcxMTI

**Comment by torch2424** [comment]
https://www.youtube.com/watch?v=DjIMoVlAhYo

**Comment by torch2424** [comment]
http://www.comm.utoronto.ca/~jli/windowxp.rdesktop.tunnel_files/2.PNG

**Comment by torch2424** [comment]
https://www.wikihow.com/images/d/d3/Create-a-User-Group-in-Windows-XP-Step-12.jpg

**Comment by torch2424** [comment]
Done :smile:
