### ISSUE TITLE
Add examples of Dropdown and Loader to the demo

### ISSUE THREAD

**Issue by smiile8888** [torch2424/aesthetic-css#30]
There are `Loader` and `Dropdown` under Elements in the demo website but no piece of code of them.

**Comment by torch2424** [comment]
Oops! I must have forgot to add them! Thanks for the issue! :+1: 

Feel free to open a PR for the fix, or, I could get around to this once I get the time :smile:

**Comment by torch2424** [comment]
Closed by #31 :smile:
